apiVersion: batch/v1
kind: Job
metadata:
  name: train-pod
spec:
  template:
    spec:
      containers:
      - name: train-pod
        imagePullPolicy: Always
        image: rachitjain2706/streamtest
        # command: ["./a.out"]
      restartPolicy: Never