apiVersion: batch/v1
kind: Job
metadata:
  name: sysbench-client
spec:
  template:
    spec:
      containers:
      - name: sysbench-client
        imagePullPolicy: Always
        image: perconalab/sysbench:latest
        command: ["sysbench", "--cpu-max-prime=30000", "--threads=2", "cpu", "run"]
        volumeMounts:
        - name: rachit-volume
          mountPath: /mnt
      restartPolicy: Never
      volumes:
        - name: rachit-volume
          persistentVolumeClaim:
            claimName: rachit-pvc